version: '3.1'

services:
  web:
    image: croneu/neos:7.3-behat
    hostname: behat-runner
    ports:
      - '5900:5900'
    environment:
      # use a separate DB container for testing
      DB_HOST: db
      DB_DATABASE: db
      COMPOSER_INSTALL_PARAMS: '--dev --prefer-dist'
