---
version: '3.1'

services:
  web:
    image: croneu/neos
    hostname: neos-playground
    ports:
    - '8080:8080'
    - '1122:22'
    links:
    - db
    volumes:
    - data:/data
    - .:/src
    environment:
      WWW_PORT: 8080
      SITE_PACKAGE: 'Neos.Demo'
      ADMIN_PASSWORD: 'password'
      IMPORT_GITHUB_PUB_KEYS: ${GITHUB_USERNAME}
      COMPOSER_INSTALL_PARAMS: '--prefer-dist'
  db:
    image: mariadb:10.3
    expose:
    - 3306
    volumes:
    - /var/lib/data
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  data:
