name: Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
        COMPOSER_VERSION: 2

    steps:
      - uses: actions/checkout@v2

      - name: Configure Composer (get version and path)
        id: composer-config
        run: |
          echo "::set-output name=major-version::$(composer --version | perl -pe '($_)=/\b(\d)\d*\.\d+\.\d+/;')"
          echo "::set-output name=cache-dir::$(composer config cache-dir)"

      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-config.outputs.cache-dir }}
          key: composer-v${{ steps.composer-config.outputs.major-version }}

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: Packages
          key: composer-build-${{ hashFiles('**/composer.lock') }}

      - name: Run composer install
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check docker-compose up and basic rendering
        run: |
          docker-compose run --rm --service-ports web bash -c "sleep 2 ; curl -s http://localhost:8081/ | grep 'powered by Neos'"

      - name: Run Behat Test Suite
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.behat.yml run -T --rm --service-ports web \
            sh -c 's6-svwait -U /var/run/s6/services/selenium ; sudo -u www-data cd /data/www/Packages/Application/CRON.BehatTester/Tests/Behavior /data/www/bin/behat' \
            2>/dev/null
