name: Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      -
        name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      -
        name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: Packages
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      -
        name: Run composer install
        run: |
          composer install
      -
        name: Check docker-compose up and basic rendering
        run: |
          docker-compose run --rm --service-ports web bash -c "sleep 2 ; curl -s http://localhost:8081/ | grep 'powered by Neos'"
      -
        name: Run Behat Test Suite
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.behat.yml run -T --rm --service-ports web \
            sh -c 's6-svwait -U /var/run/s6/services/selenium ; sudo -u www-data cd /data/www/Packages/Application/CRON.BehatTester/Tests/Behavior /data/www/bin/behat' \
            2>/dev/null
